#include <map>
#include <string>
#include <unordered_map>
#include <vector>

std::unordered_map<std::string, std::vector<std::pair<std::string, int>>> rules{
    { { "muted lime",
        { { "wavy lime", 1 }, { "vibrant green", 1 }, { "light yellow", 3 } } },
      { "light red", { { "clear indigo", 2 }, { "light lime", 3 } } },
      { "wavy beige", { { "faded chartreuse", 4 } } },
      { "muted blue", { { "mirrored tan", 3 } } },
      { "vibrant cyan",
        { { "drab beige", 4 }, { "vibrant maroon", 4 }, { "dull coral", 2 } } },
      { "posh indigo",
        { { "dim cyan", 1 }, { "striped violet", 4 }, { "posh olive", 2 } } },
      { "dark black",
        { { "dotted purple", 5 },
          { "dotted orange", 3 },
          { "shiny gold", 5 },
          { "wavy brown", 3 } } },
      { "dull teal", { { "posh aqua", 1 } } },
      { "dim aqua",
        { { "muted indigo", 3 },
          { "vibrant green", 5 },
          { "dotted teal", 3 } } },
      { "clear bronze",
        { { "plaid gold", 1 },
          { "pale tan", 4 },
          { "light teal", 1 },
          { "dim lavender", 5 } } },
      { "shiny fuchsia", { { "striped orange", 5 }, { "faded plum", 2 } } },
      { "dim bronze", { { "plaid tan", 2 }, { "muted green", 4 } } },
      { "muted white", { { "wavy black", 1 }, { "striped olive", 2 } } },
      { "wavy maroon",
        { { "striped magenta", 3 },
          { "bright teal", 3 },
          { "dark crimson", 2 } } },
      { "muted beige",
        { { "dull plum", 4 },
          { "plaid fuchsia", 2 },
          { "clear coral", 3 },
          { "clear red", 1 } } },
      { "drab chartreuse",
        { { "dull gray", 2 }, { "striped olive", 2 }, { "dark aqua", 2 } } },
      { "plaid turquoise", { { "muted teal", 1 } } },
      { "muted maroon",
        { { "faded chartreuse", 1 },
          { "wavy gray", 1 },
          { "faded black", 5 },
          { "posh tan", 2 } } },
      { "muted bronze", { { "muted white", 1 } } },
      { "muted teal", { { "striped beige", 1 } } },
      { "faded indigo", { { "mirrored green", 5 } } },
      { "drab tan", { { "dim lavender", 4 } } },
      { "bright turquoise", { { "pale olive", 2 }, { "posh salmon", 4 } } },
      { "dull aqua",
        { { "dark orange", 2 }, { "pale aqua", 2 }, { "faded plum", 1 } } },
      { "striped coral", { { "wavy purple", 3 }, { "dull gray", 2 } } },
      { "muted chartreuse", { { "dark purple", 3 }, { "posh gray", 2 } } },
      { "wavy plum",
        { { "dark lavender", 2 },
          { "shiny turquoise", 2 },
          { "wavy beige", 5 },
          { "pale maroon", 5 } } },
      { "vibrant maroon",
        { { "light lime", 1 },
          { "light silver", 1 },
          { "bright orange", 5 },
          { "shiny red", 2 } } },
      { "mirrored purple",
        { { "bright olive", 3 },
          { "bright yellow", 3 },
          { "muted white", 5 } } },
      { "muted magenta", { { "plaid indigo", 5 } } },
      { "drab lavender",
        { { "faded beige", 1 }, { "muted gray", 2 }, { "dotted purple", 2 } } },
      { "plaid cyan", { { "plaid violet", 4 }, { "posh chartreuse", 5 } } },
      { "plaid aqua",
        { { "wavy gray", 2 }, { "light fuchsia", 4 }, { "muted white", 4 } } },
      { "wavy bronze",
        { { "light bronze", 4 },
          { "light tomato", 3 },
          { "shiny tomato", 5 } } },
      { "wavy aqua",
        { { "plaid crimson", 4 }, { "muted brown", 3 }, { "pale tan", 1 } } },
      { "bright violet",
        { { "wavy tan", 1 }, { "light coral", 4 }, { "vibrant plum", 1 } } },
      { "pale yellow",
        { { "light lime", 4 },
          { "striped violet", 2 },
          { "plaid orange", 1 },
          { "dull lavender", 3 } } },
      { "plaid olive",
        { { "mirrored magenta", 1 },
          { "posh silver", 3 },
          { "plaid brown", 1 } } },
      { "wavy brown", { { "shiny black", 4 }, { "wavy plum", 3 } } },
      { "clear turquoise", { { "dotted beige", 5 } } },
      { "striped fuchsia", { { "dim tan", 2 } } },
      { "pale coral", { { "plaid coral", 1 }, { "striped salmon", 5 } } },
      { "plaid magenta",
        { { "plaid aqua", 4 }, { "dim cyan", 2 }, { "vibrant teal", 2 } } },
      { "dim beige", { { "shiny gold", 5 }, { "wavy brown", 2 } } },
      { "clear violet", { { "striped silver", 2 } } },
      { "light lime", { { "muted teal", 5 } } },
      { "pale plum", { { "vibrant lavender", 2 } } },
      { "drab black",
        { { "light white", 3 },
          { "dim tomato", 2 },
          { "dull yellow", 3 },
          { "plaid coral", 2 } } },
      { "vibrant lime",
        { { "wavy gray", 5 },
          { "striped green", 5 },
          { "striped black", 5 } } },
      { "faded fuchsia", { { "shiny aqua", 3 } } },
      { "vibrant olive", { { "striped olive", 2 } } },
      { "dark indigo", { { "pale maroon", 5 }, { "striped turquoise", 2 } } },
      { "dark cyan",
        { { "light gold", 3 }, { "plaid lime", 1 }, { "dim indigo", 1 } } },
      { "clear tomato", { { "plaid tan", 3 }, { "vibrant blue", 2 } } },
      { "muted yellow", { { "dotted coral", 2 } } },
      { "muted brown",
        { { "vibrant green", 1 },
          { "bright green", 3 },
          { "plaid fuchsia", 2 } } },
      { "dark bronze", { { "clear orange", 2 } } },
      { "dotted turquoise",
        { { "faded black", 4 },
          { "plaid crimson", 3 },
          { "faded beige", 3 } } },
      { "shiny violet",
        { { "muted blue", 4 },
          { "light purple", 2 },
          { "striped magenta", 5 },
          { "dark black", 3 } } },
      { "dotted orange",
        { { "striped tan", 3 },
          { "posh brown", 2 },
          { "muted white", 2 },
          { "dark crimson", 5 } } },
      { "shiny gold",
        { { "clear coral", 1 },
          { "muted green", 1 },
          { "muted teal", 5 },
          { "dull olive", 4 } } },
      { "clear brown", { { "shiny tomato", 1 } } },
      { "shiny beige", { { "dotted chartreuse", 4 } } },
      { "dotted tomato", { { "dull aqua", 5 } } },
      { "dull black", { { "muted purple", 2 } } },
      { "wavy turquoise",
        { { "striped beige", 5 },
          { "dark silver", 2 },
          { "light beige", 2 },
          { "dull olive", 5 } } },
      { "bright coral",
        { { "pale crimson", 4 },
          { "striped coral", 4 },
          { "drab cyan", 3 },
          { "vibrant aqua", 4 } } },
      { "mirrored salmon", { { "wavy orange", 1 }, { "dark lime", 1 } } },
      { "clear chartreuse", { { "muted indigo", 4 }, { "dotted gray", 5 } } },
      { "dim chartreuse",
        { { "clear lime", 1 },
          { "muted gray", 3 },
          { "vibrant blue", 5 },
          { "mirrored gold", 4 } } },
      { "vibrant purple",
        { { "dull brown", 4 },
          { "clear aqua", 5 },
          { "bright bronze", 2 },
          { "shiny lavender", 5 } } },
      { "pale turquoise", { { "light black", 3 }, { "dim tan", 1 } } },
      { "mirrored black", { { "wavy beige", 1 } } },
      { "striped white",
        { { "dim chartreuse", 4 },
          { "pale lime", 2 },
          { "faded orange", 1 } } },
      { "faded bronze", { { "drab cyan", 5 } } },
      { "dull coral", { { "dull crimson", 5 }, { "plaid silver", 3 } } },
      { "posh gray",
        { { "muted indigo", 4 }, { "bright cyan", 4 }, { "faded black", 1 } } },
      { "vibrant bronze",
        { { "posh crimson", 4 },
          { "mirrored silver", 4 },
          { "dark turquoise", 1 },
          { "pale maroon", 1 } } },
      { "posh lavender",
        { { "vibrant gold", 1 },
          { "faded maroon", 3 },
          { "striped magenta", 4 },
          { "wavy gold", 3 } } },
      { "clear olive",
        { { "posh tomato", 1 }, { "clear lime", 2 }, { "plaid yellow", 1 } } },
      { "bright orange",
        { { "light aqua", 4 },
          { "vibrant teal", 3 },
          { "dull crimson", 5 },
          { "dark fuchsia", 3 } } },
      { "dotted lavender",
        { { "posh beige", 1 }, { "faded cyan", 5 }, { "dark olive", 1 } } },
      { "posh beige", { { "dotted blue", 3 }, { "faded indigo", 4 } } },
      { "dull indigo", { { "clear green", 4 }, { "muted bronze", 5 } } },
      { "mirrored brown",
        { { "muted beige", 5 },
          { "dull chartreuse", 3 },
          { "shiny black", 4 },
          { "dim green", 1 } } },
      { "bright silver",
        { { "clear white", 3 }, { "light tomato", 5 }, { "plaid blue", 5 } } },
      { "dotted teal", {} },
      { "light brown", { { "faded indigo", 1 }, { "dotted coral", 3 } } },
      { "light indigo",
        { { "plaid red", 1 },
          { "vibrant magenta", 5 },
          { "pale lavender", 4 } } },
      { "drab beige", { { "dotted gold", 1 }, { "clear black", 3 } } },
      { "striped orange",
        { { "shiny red", 3 }, { "striped olive", 4 }, { "posh maroon", 1 } } },
      { "bright lavender", {} },
      { "clear yellow",
        { { "mirrored green", 5 },
          { "striped red", 4 },
          { "plaid magenta", 3 },
          { "bright lavender", 1 } } },
      { "pale bronze",
        { { "bright beige", 4 }, { "muted beige", 4 }, { "pale salmon", 3 } } },
      { "light salmon", { { "shiny brown", 3 } } },
      { "shiny plum", { { "dotted turquoise", 5 } } },
      { "dotted red",
        { { "muted bronze", 2 },
          { "dull yellow", 2 },
          { "drab turquoise", 4 } } },
      { "faded white", { { "striped beige", 1 } } },
      { "bright olive", { { "posh brown", 1 }, { "mirrored red", 2 } } },
      { "light gray", { { "wavy lavender", 5 }, { "vibrant yellow", 5 } } },
      { "mirrored indigo", { { "wavy turquoise", 1 }, { "muted green", 5 } } },
      { "light black",
        { { "light fuchsia", 3 },
          { "plaid fuchsia", 3 },
          { "mirrored green", 5 } } },
      { "striped maroon",
        { { "dull fuchsia", 4 },
          { "striped olive", 1 },
          { "mirrored gold", 1 },
          { "light violet", 4 } } },
      { "mirrored silver",
        { { "posh tan", 2 },
          { "mirrored magenta", 2 },
          { "dark orange", 1 } } },
      { "pale aqua", { { "dim tan", 5 }, { "muted black", 4 } } },
      { "pale gray", { { "clear plum", 2 } } },
      { "faded turquoise", { { "faded black", 5 }, { "shiny black", 3 } } },
      { "dotted indigo",
        { { "plaid green", 4 },
          { "dull brown", 4 },
          { "plaid magenta", 1 },
          { "plaid tomato", 2 } } },
      { "vibrant silver", { { "drab chartreuse", 3 } } },
      { "dotted crimson",
        { { "drab coral", 1 },
          { "shiny red", 2 },
          { "dotted plum", 2 },
          { "mirrored yellow", 4 } } },
      { "clear orange",
        { { "wavy black", 4 },
          { "drab coral", 2 },
          { "bright lavender", 1 },
          { "dull olive", 2 } } },
      { "mirrored violet", { { "striped tan", 4 } } },
      { "bright tan",
        { { "mirrored gold", 1 },
          { "dotted turquoise", 1 },
          { "wavy orange", 4 } } },
      { "dull bronze", { { "shiny chartreuse", 3 }, { "dark beige", 2 } } },
      { "vibrant white", { { "plaid tan", 4 }, { "wavy black", 1 } } },
      { "wavy green",
        { { "muted fuchsia", 2 },
          { "plaid gold", 3 },
          { "striped green", 3 },
          { "dim cyan", 5 } } },
      { "striped brown", { { "vibrant olive", 3 }, { "plaid orange", 2 } } },
      { "wavy lavender",
        { { "muted orange", 2 },
          { "clear maroon", 4 },
          { "bright tomato", 5 } } },
      { "bright purple", { { "dim crimson", 4 } } },
      { "pale fuchsia", { { "bright lime", 5 } } },
      { "posh aqua",
        { { "clear lime", 5 },
          { "shiny turquoise", 1 },
          { "bright cyan", 5 },
          { "dim chartreuse", 2 } } },
      { "dark olive",
        { { "shiny tan", 5 }, { "plaid red", 5 }, { "pale lavender", 5 } } },
      { "striped silver", { { "bright plum", 3 } } },
      { "striped tomato", { { "pale maroon", 1 }, { "clear yellow", 1 } } },
      { "faded beige", { { "light fuchsia", 1 } } },
      { "plaid green", { { "light fuchsia", 5 } } },
      { "drab silver", { { "vibrant white", 4 } } },
      { "striped indigo", { { "shiny green", 4 }, { "dark beige", 2 } } },
      { "mirrored teal", { { "muted green", 3 }, { "muted gray", 5 } } },
      { "posh gold",
        { { "wavy beige", 3 },
          { "muted lavender", 5 },
          { "striped tan", 1 } } },
      { "wavy red", { { "dim beige", 2 } } },
      { "dull plum", { { "drab coral", 2 }, { "wavy black", 3 } } },
      { "bright crimson",
        { { "posh silver", 2 }, { "vibrant plum", 3 }, { "posh brown", 5 } } },
      { "clear gray", { { "dotted white", 1 }, { "posh aqua", 2 } } },
      { "striped aqua",
        { { "muted black", 1 },
          { "dim bronze", 5 },
          { "striped olive", 3 },
          { "plaid turquoise", 1 } } },
      { "dark tomato",
        { { "dull olive", 2 },
          { "plaid aqua", 1 },
          { "faded fuchsia", 4 },
          { "muted gray", 4 } } },
      { "vibrant yellow",
        { { "dim blue", 5 }, { "dim crimson", 5 }, { "dotted aqua", 1 } } },
      { "shiny salmon",
        { { "bright lavender", 4 },
          { "faded black", 2 },
          { "mirrored salmon", 5 } } },
      { "wavy salmon",
        { { "plaid aqua", 1 },
          { "mirrored fuchsia", 2 },
          { "muted green", 2 } } },
      { "faded cyan", { { "plaid fuchsia", 5 }, { "dull gray", 4 } } },
      { "clear coral", { { "striped olive", 1 } } },
      { "bright white", { { "muted gray", 1 } } },
      { "dim salmon", { { "faded red", 1 }, { "striped plum", 2 } } },
      { "dotted silver",
        { { "faded lime", 5 },
          { "drab black", 2 },
          { "mirrored teal", 2 },
          { "drab tomato", 2 } } },
      { "bright teal", { { "dotted gray", 5 } } },
      { "faded red", { { "light purple", 3 }, { "plaid yellow", 5 } } },
      { "muted salmon", { { "clear yellow", 3 } } },
      { "shiny turquoise", { { "dark lavender", 2 }, { "dark crimson", 1 } } },
      { "muted indigo", { { "dark lavender", 4 }, { "posh olive", 1 } } },
      { "wavy gray", {} },
      { "muted olive",
        { { "bright tomato", 3 },
          { "plaid coral", 4 },
          { "dull orange", 4 },
          { "wavy brown", 2 } } },
      { "clear black",
        { { "dim chartreuse", 1 }, { "dark aqua", 5 }, { "dotted teal", 5 } } },
      { "faded yellow", { { "drab salmon", 1 }, { "bright lavender", 1 } } },
      { "shiny yellow",
        { { "dark olive", 3 }, { "bright tomato", 1 }, { "dim fuchsia", 3 } } },
      { "clear blue",
        { { "light coral", 2 },
          { "faded beige", 2 },
          { "muted indigo", 4 },
          { "faded blue", 1 } } },
      { "dim lime",
        { { "striped tan", 5 }, { "light black", 4 }, { "dark orange", 1 } } },
      { "wavy coral",
        { { "mirrored black", 2 },
          { "vibrant coral", 4 },
          { "pale chartreuse", 1 } } },
      { "wavy fuchsia", { { "shiny silver", 4 } } },
      { "dim silver", { { "clear blue", 3 } } },
      { "plaid chartreuse", { { "clear plum", 2 } } },
      { "pale blue", { { "pale magenta", 4 } } },
      { "drab red", { { "plaid cyan", 3 }, { "light yellow", 3 } } },
      { "dull gold", { { "clear lime", 5 }, { "plaid coral", 5 } } },
      { "shiny indigo", { { "dim bronze", 3 }, { "dotted teal", 5 } } },
      { "light purple", { { "light lime", 5 }, { "shiny plum", 1 } } },
      { "mirrored cyan", { { "clear lime", 5 } } },
      { "posh chartreuse", { { "striped olive", 2 } } },
      { "dark gray", { { "vibrant maroon", 5 }, { "dark olive", 2 } } },
      { "clear lavender",
        { { "striped magenta", 3 },
          { "pale lavender", 3 },
          { "dotted chartreuse", 2 },
          { "dim tan", 4 } } },
      { "faded lavender",
        { { "striped lavender", 5 },
          { "mirrored yellow", 2 },
          { "bright purple", 4 } } },
      { "striped tan", { { "drab coral", 3 }, { "vibrant indigo", 3 } } },
      { "dim violet",
        { { "wavy black", 4 },
          { "faded indigo", 3 },
          { "wavy gray", 2 },
          { "striped red", 5 } } },
      { "dotted magenta", { { "shiny indigo", 5 }, { "mirrored red", 3 } } },
      { "shiny blue",
        { { "light tan", 4 },
          { "striped black", 4 },
          { "vibrant teal", 1 },
          { "shiny gray", 4 } } },
      { "bright gray", { { "clear tomato", 5 }, { "dark lavender", 5 } } },
      { "dark turquoise",
        { { "dull lime", 5 }, { "dim green", 3 }, { "pale tan", 3 } } },
      { "clear beige", { { "drab aqua", 3 } } },
      { "pale olive", { { "dark green", 4 }, { "posh crimson", 1 } } },
      { "posh fuchsia",
        { { "dim green", 3 },
          { "posh maroon", 3 },
          { "posh olive", 1 },
          { "muted fuchsia", 4 } } },
      { "posh bronze",
        { { "striped olive", 5 }, { "dark lavender", 2 }, { "posh tan", 4 } } },
      { "shiny bronze", { { "dotted plum", 4 }, { "clear indigo", 4 } } },
      { "wavy magenta",
        { { "dim chartreuse", 2 },
          { "mirrored gold", 2 },
          { "wavy gold", 2 } } },
      { "dull yellow", { { "plaid tan", 4 } } },
      { "mirrored tomato", { { "light violet", 3 } } },
      { "light turquoise", { { "bright yellow", 3 }, { "drab blue", 1 } } },
      { "plaid maroon", { { "plaid magenta", 2 } } },
      { "pale silver", { { "wavy bronze", 2 }, { "striped tan", 3 } } },
      { "striped blue",
        { { "dark crimson", 1 },
          { "dull purple", 4 },
          { "bright tomato", 4 } } },
      { "faded blue",
        { { "posh olive", 2 },
          { "clear silver", 1 },
          { "faded turquoise", 5 } } },
      { "dark blue", { { "vibrant gray", 5 }, { "pale lavender", 3 } } },
      { "light fuchsia",
        { { "dotted teal", 1 }, { "shiny red", 2 }, { "bright cyan", 4 } } },
      { "dull chartreuse", { { "dull olive", 5 }, { "dull gray", 2 } } },
      { "pale orange", { { "striped lavender", 2 }, { "dotted red", 3 } } },
      { "dark silver",
        { { "muted white", 1 },
          { "striped aqua", 3 },
          { "dim aqua", 3 },
          { "striped tan", 2 } } },
      { "dark lavender",
        { { "wavy gray", 3 },
          { "dim chartreuse", 4 },
          { "bright lavender", 1 },
          { "muted gray", 3 } } },
      { "light beige", { { "dim aqua", 4 }, { "mirrored teal", 5 } } },
      { "plaid violet", { { "clear plum", 2 }, { "striped olive", 2 } } },
      { "plaid orange",
        { { "dim maroon", 1 }, { "dim bronze", 1 }, { "muted white", 5 } } },
      { "faded crimson", { { "faded cyan", 3 } } },
      { "muted plum", { { "bright teal", 5 } } },
      { "striped crimson",
        { { "shiny violet", 3 },
          { "striped beige", 4 },
          { "wavy violet", 5 } } },
      { "shiny lime", { { "dim green", 5 }, { "mirrored black", 5 } } },
      { "muted lavender",
        { { "mirrored magenta", 4 },
          { "wavy yellow", 4 },
          { "pale gold", 5 },
          { "light cyan", 2 } } },
      { "drab aqua",
        { { "plaid blue", 3 },
          { "pale bronze", 3 },
          { "bright magenta", 3 } } },
      { "dark yellow", { { "bright salmon", 4 }, { "dim yellow", 2 } } },
      { "posh teal", { { "clear crimson", 1 } } },
      { "clear fuchsia",
        { { "vibrant blue", 1 },
          { "shiny lavender", 2 },
          { "faded teal", 3 },
          { "plaid green", 4 } } },
      { "bright yellow",
        { { "mirrored coral", 4 },
          { "dull purple", 2 },
          { "dim indigo", 3 },
          { "dark white", 5 } } },
      { "pale purple",
        { { "vibrant olive", 2 },
          { "dark fuchsia", 1 },
          { "faded turquoise", 3 } } },
      { "dotted coral", { { "dark crimson", 4 } } },
      { "plaid beige",
        { { "striped maroon", 2 },
          { "mirrored fuchsia", 4 },
          { "shiny turquoise", 5 },
          { "clear plum", 3 } } },
      { "plaid white", { { "posh chartreuse", 5 }, { "dark crimson", 4 } } },
      { "shiny black",
        { { "dim brown", 4 }, { "plaid tan", 5 }, { "plaid orange", 5 } } },
      { "dim teal", { { "wavy aqua", 1 } } },
      { "dim yellow", { { "muted bronze", 2 }, { "bright indigo", 1 } } },
      { "dim tan",
        { { "plaid turquoise", 1 },
          { "vibrant plum", 4 },
          { "plaid aqua", 2 } } },
      { "bright salmon",
        { { "dim blue", 3 }, { "wavy gray", 5 }, { "bright maroon", 2 } } },
      { "posh plum",
        { { "dark cyan", 2 },
          { "bright orange", 1 },
          { "dotted crimson", 1 },
          { "dark tan", 4 } } },
      { "muted crimson",
        { { "striped beige", 1 },
          { "muted salmon", 4 },
          { "faded tan", 1 },
          { "dull fuchsia", 3 } } },
      { "mirrored lavender",
        { { "light black", 3 }, { "posh salmon", 4 }, { "shiny black", 2 } } },
      { "dim olive",
        { { "bright green", 2 },
          { "bright magenta", 3 },
          { "striped silver", 4 },
          { "vibrant indigo", 1 } } },
      { "faded coral",
        { { "posh blue", 5 }, { "dotted maroon", 5 }, { "dark maroon", 3 } } },
      { "striped cyan",
        { { "vibrant purple", 2 },
          { "shiny silver", 2 },
          { "clear tan", 5 },
          { "muted orange", 4 } } },
      { "striped beige",
        { { "bright lavender", 2 },
          { "mirrored gold", 3 },
          { "dull fuchsia", 4 },
          { "dull gray", 4 } } },
      { "mirrored magenta",
        { { "posh crimson", 5 },
          { "pale magenta", 1 },
          { "striped maroon", 3 },
          { "shiny turquoise", 4 } } },
      { "vibrant chartreuse", { { "light beige", 2 }, { "dark white", 4 } } },
      { "mirrored fuchsia", { { "plaid red", 4 } } },
      { "vibrant turquoise",
        { { "light teal", 4 },
          { "plaid salmon", 5 },
          { "muted tan", 2 },
          { "posh tomato", 5 } } },
      { "faded gray", { { "dull white", 2 }, { "plaid orange", 1 } } },
      { "bright bronze",
        { { "muted teal", 4 }, { "dark crimson", 3 }, { "posh tan", 4 } } },
      { "plaid lime", { { "striped turquoise", 3 } } },
      { "pale teal",
        { { "shiny silver", 5 }, { "posh plum", 4 }, { "plaid salmon", 3 } } },
      { "dark chartreuse",
        { { "bright plum", 5 },
          { "faded beige", 2 },
          { "vibrant chartreuse", 1 } } },
      { "dull crimson",
        { { "light beige", 5 },
          { "muted purple", 4 },
          { "dotted chartreuse", 4 },
          { "faded turquoise", 4 } } },
      { "dotted salmon",
        { { "faded indigo", 3 }, { "dotted gold", 1 }, { "light lime", 3 } } },
      { "bright black",
        { { "dim yellow", 2 }, { "vibrant coral", 3 }, { "light coral", 5 } } },
      { "plaid blue",
        { { "mirrored tomato", 4 },
          { "faded fuchsia", 5 },
          { "dull chartreuse", 5 } } },
      { "shiny white",
        { { "dim maroon", 4 },
          { "dim gray", 1 },
          { "light white", 2 },
          { "dull tan", 3 } } },
      { "muted cyan", { { "pale cyan", 2 } } },
      { "dim red", { { "faded indigo", 1 } } },
      { "mirrored tan",
        { { "striped magenta", 4 }, { "clear chartreuse", 1 } } },
      { "bright blue", { { "wavy turquoise", 2 } } },
      { "pale tan", { { "faded black", 2 } } },
      { "dark green", { { "pale salmon", 1 } } },
      { "pale beige", { { "bright chartreuse", 2 }, { "faded bronze", 4 } } },
      { "dotted gold",
        { { "wavy black", 2 },
          { "dotted coral", 1 },
          { "dim maroon", 4 },
          { "dark green", 5 } } },
      { "dark magenta", { { "wavy yellow", 2 }, { "dark cyan", 1 } } },
      { "bright chartreuse",
        { { "dotted blue", 4 },
          { "shiny aqua", 3 },
          { "muted crimson", 1 },
          { "dull blue", 4 } } },
      { "dotted black",
        { { "posh gray", 4 },
          { "striped white", 4 },
          { "faded green", 2 },
          { "shiny indigo", 2 } } },
      { "posh red",
        { { "clear chartreuse", 4 },
          { "plaid maroon", 4 },
          { "striped orange", 2 } } },
      { "dark aqua", { { "vibrant indigo", 1 }, { "dark crimson", 1 } } },
      { "drab indigo", { { "vibrant salmon", 2 }, { "shiny purple", 2 } } },
      { "dull lavender",
        { { "vibrant plum", 4 },
          { "vibrant indigo", 3 },
          { "clear lime", 3 } } },
      { "dull magenta",
        { { "mirrored white", 4 },
          { "clear olive", 3 },
          { "striped plum", 5 } } },
      { "dotted chartreuse", { { "striped beige", 3 }, { "wavy gray", 4 } } },
      { "dotted yellow", { { "plaid white", 3 }, { "posh gray", 2 } } },
      { "vibrant red", { { "clear cyan", 5 } } },
      { "dim orange", { { "drab chartreuse", 4 }, { "muted teal", 3 } } },
      { "shiny brown", { { "dim maroon", 3 } } },
      { "posh green", { { "muted brown", 5 }, { "dark crimson", 1 } } },
      { "pale lime",
        { { "muted gray", 3 },
          { "dotted coral", 5 },
          { "faded black", 5 },
          { "vibrant white", 2 } } },
      { "dim maroon", { { "wavy gray", 2 }, { "plaid fuchsia", 4 } } },
      { "bright beige",
        { { "striped maroon", 3 },
          { "striped magenta", 2 },
          { "light teal", 3 },
          { "shiny red", 2 } } },
      { "drab magenta", { { "posh olive", 2 } } },
      { "wavy white",
        { { "plaid tomato", 3 },
          { "dotted gray", 1 },
          { "mirrored bronze", 2 } } },
      { "posh coral",
        { { "wavy coral", 2 }, { "mirrored tan", 5 }, { "pale gray", 1 } } },
      { "plaid gray",
        { { "faded green", 3 },
          { "faded olive", 5 },
          { "drab white", 4 },
          { "wavy green", 3 } } },
      { "bright plum",
        { { "dark aqua", 1 }, { "shiny red", 4 }, { "vibrant white", 2 } } },
      { "plaid tomato", { { "light lime", 2 }, { "vibrant white", 3 } } },
      { "pale brown", { { "faded brown", 1 } } },
      { "muted gray",
        { { "posh olive", 3 },
          { "plaid fuchsia", 4 },
          { "vibrant blue", 3 } } },
      { "dotted green",
        { { "dim lavender", 1 },
          { "striped chartreuse", 4 },
          { "bright maroon", 3 } } },
      { "striped yellow",
        { { "pale white", 4 },
          { "bright blue", 2 },
          { "faded orange", 5 },
          { "dull violet", 2 } } },
      { "mirrored chartreuse",
        { { "shiny indigo", 2 }, { "mirrored teal", 2 } } },
      { "posh olive",
        { { "muted purple", 4 }, { "dull gray", 1 }, { "striped beige", 1 } } },
      { "posh salmon", { { "dim yellow", 5 }, { "dark purple", 2 } } },
      { "drab gold",
        { { "posh white", 3 },
          { "dotted salmon", 3 },
          { "vibrant coral", 2 } } },
      { "faded silver", { { "wavy magenta", 2 } } },
      { "dim blue", { { "clear lime", 2 } } },
      { "faded black",
        { { "dark crimson", 4 },
          { "dark aqua", 2 },
          { "mirrored teal", 1 },
          { "dull brown", 4 } } },
      { "striped lavender",
        { { "plaid red", 4 },
          { "light black", 1 },
          { "bright cyan", 2 },
          { "muted tan", 2 } } },
      { "mirrored olive",
        { { "plaid beige", 2 }, { "wavy aqua", 1 }, { "faded tomato", 3 } } },
      { "wavy lime", { { "mirrored brown", 1 }, { "posh cyan", 5 } } },
      { "dim crimson", { { "drab chartreuse", 2 }, { "posh lavender", 1 } } },
      { "dim black",
        { { "dull black", 2 },
          { "vibrant maroon", 3 },
          { "light fuchsia", 2 } } },
      { "drab cyan", { { "striped turquoise", 3 } } },
      { "dim brown",
        { { "dim orange", 5 },
          { "dull brown", 5 },
          { "dotted teal", 1 },
          { "dark white", 3 } } },
      { "vibrant magenta", { { "light crimson", 1 }, { "light maroon", 4 } } },
      { "dotted fuchsia",
        { { "dark green", 1 }, { "wavy gold", 3 }, { "bright indigo", 3 } } },
      { "light crimson", { { "pale chartreuse", 2 } } },
      { "posh crimson",
        { { "plaid tan", 5 }, { "dark lavender", 1 }, { "light lime", 4 } } },
      { "dark fuchsia",
        { { "mirrored coral", 5 },
          { "vibrant olive", 5 },
          { "light black", 4 } } },
      { "faded chartreuse",
        { { "drab coral", 3 },
          { "dim chartreuse", 1 },
          { "dotted chartreuse", 4 },
          { "muted teal", 1 } } },
      { "dotted lime",
        { { "shiny turquoise", 1 },
          { "vibrant plum", 3 },
          { "vibrant teal", 5 } } },
      { "light teal", { { "bright plum", 3 } } },
      { "shiny chartreuse", { { "vibrant green", 5 }, { "dim blue", 1 } } },
      { "vibrant tomato",
        { { "clear tan", 1 },
          { "faded magenta", 3 },
          { "clear cyan", 2 },
          { "dark silver", 2 } } },
      { "posh cyan",
        { { "vibrant white", 1 }, { "dull white", 2 }, { "drab coral", 3 } } },
      { "dim white",
        { { "shiny aqua", 5 },
          { "shiny bronze", 2 },
          { "plaid turquoise", 1 },
          { "dull tomato", 4 } } },
      { "vibrant plum",
        { { "posh olive", 3 },
          { "dark crimson", 4 },
          { "mirrored gold", 3 } } },
      { "clear cyan",
        { { "shiny cyan", 5 },
          { "clear fuchsia", 2 },
          { "plaid lime", 5 },
          { "muted green", 1 } } },
      { "mirrored red",
        { { "dotted coral", 5 }, { "shiny gold", 3 }, { "clear plum", 2 } } },
      { "mirrored gray",
        { { "clear black", 3 },
          { "bright fuchsia", 1 },
          { "drab teal", 1 },
          { "faded bronze", 5 } } },
      { "posh orange", { { "bright cyan", 2 }, { "muted gray", 1 } } },
      { "plaid salmon",
        { { "dim maroon", 5 },
          { "pale chartreuse", 1 },
          { "posh fuchsia", 3 },
          { "dark turquoise", 3 } } },
      { "dull silver",
        { { "mirrored maroon", 2 },
          { "plaid lavender", 2 },
          { "dotted red", 1 } } },
      { "light plum",
        { { "light white", 4 },
          { "wavy lavender", 3 },
          { "vibrant salmon", 5 } } },
      { "dotted white",
        { { "light aqua", 5 }, { "dim brown", 4 }, { "drab brown", 3 } } },
      { "drab green",
        { { "wavy black", 1 },
          { "vibrant orange", 5 },
          { "wavy orange", 5 },
          { "muted purple", 1 } } },
      { "pale red", { { "dim tomato", 3 } } },
      { "clear silver", { { "clear lime", 3 } } },
      { "faded gold",
        { { "faded orange", 4 }, { "light bronze", 4 }, { "wavy gray", 3 } } },
      { "drab tomato",
        { { "clear black", 3 }, { "dark white", 1 }, { "light silver", 5 } } },
      { "dull tomato",
        { { "vibrant indigo", 5 },
          { "dotted plum", 5 },
          { "dull black", 4 } } },
      { "light gold",
        { { "bright gold", 2 }, { "faded white", 5 }, { "striped gold", 3 } } },
      { "faded green", { { "light purple", 1 } } },
      { "striped gray", { { "muted gray", 4 } } },
      { "striped plum", { { "dim coral", 2 } } },
      { "dull olive", { { "pale salmon", 3 } } },
      { "bright tomato",
        { { "dim bronze", 2 },
          { "dim chartreuse", 1 },
          { "clear purple", 5 } } },
      { "wavy purple", { { "faded green", 2 } } },
      { "muted coral", { { "faded black", 1 } } },
      { "dark beige",
        { { "mirrored gold", 3 },
          { "posh brown", 4 },
          { "dotted indigo", 1 },
          { "mirrored fuchsia", 3 } } },
      { "faded plum", { { "dotted coral", 5 } } },
      { "light maroon", { { "striped violet", 3 } } },
      { "wavy orange",
        { { "plaid orange", 3 },
          { "striped turquoise", 1 },
          { "muted black", 4 },
          { "posh indigo", 2 } } },
      { "drab purple",
        { { "dull lime", 4 },
          { "posh lavender", 4 },
          { "shiny green", 4 },
          { "faded beige", 3 } } },
      { "dim fuchsia", { { "vibrant purple", 1 }, { "dim yellow", 5 } } },
      { "plaid tan",
        { { "posh maroon", 5 },
          { "plaid crimson", 3 },
          { "dim chartreuse", 5 } } },
      { "light bronze",
        { { "posh cyan", 2 },
          { "shiny indigo", 5 },
          { "faded silver", 1 },
          { "shiny brown", 5 } } },
      { "dotted gray", { { "faded beige", 3 }, { "shiny turquoise", 1 } } },
      { "dull white", { { "muted indigo", 3 }, { "clear coral", 4 } } },
      { "drab crimson", { { "dark white", 1 }, { "wavy salmon", 1 } } },
      { "clear maroon", { { "shiny tan", 1 }, { "muted brown", 3 } } },
      { "shiny green", { { "drab black", 2 }, { "mirrored brown", 3 } } },
      { "dark red", { { "faded white", 4 }, { "faded plum", 5 } } },
      { "dim purple", { { "wavy maroon", 5 }, { "pale bronze", 1 } } },
      { "shiny coral",
        { { "dull olive", 1 },
          { "wavy tomato", 2 },
          { "dark tomato", 3 },
          { "drab lime", 2 } } },
      { "muted fuchsia", { { "faded beige", 3 } } },
      { "plaid silver", { { "mirrored violet", 5 }, { "dark tomato", 5 } } },
      { "vibrant gold",
        { { "striped turquoise", 5 },
          { "shiny gray", 4 },
          { "muted maroon", 2 },
          { "dark orange", 5 } } },
      { "bright fuchsia", { { "pale red", 4 }, { "posh fuchsia", 3 } } },
      { "dark violet", { { "drab yellow", 4 } } },
      { "dim gold", { { "vibrant silver", 5 } } },
      { "posh tomato", { { "mirrored violet", 1 } } },
      { "drab yellow",
        { { "light silver", 1 },
          { "clear maroon", 4 },
          { "dotted aqua", 5 },
          { "posh maroon", 1 } } },
      { "vibrant lavender", { { "dim turquoise", 4 } } },
      { "dotted blue", { { "faded black", 3 } } },
      { "plaid crimson", { { "wavy gray", 5 }, { "striped beige", 3 } } },
      { "dim green", { { "bright cyan", 2 }, { "bright beige", 4 } } },
      { "faded brown", { { "posh cyan", 4 } } },
      { "muted violet",
        { { "posh aqua", 4 },
          { "bright yellow", 4 },
          { "drab red", 2 },
          { "dull teal", 3 } } },
      { "shiny silver", { { "plaid fuchsia", 5 } } },
      { "wavy olive",
        { { "light brown", 4 },
          { "shiny turquoise", 4 },
          { "bright orange", 1 },
          { "drab blue", 5 } } },
      { "mirrored turquoise",
        { { "dark lime", 1 },
          { "faded bronze", 1 },
          { "dark lavender", 1 },
          { "wavy turquoise", 3 } } },
      { "dark lime",
        { { "dim bronze", 3 },
          { "shiny turquoise", 5 },
          { "muted gray", 1 } } },
      { "striped gold",
        { { "faded turquoise", 3 },
          { "striped teal", 5 },
          { "posh lavender", 4 } } },
      { "light orange", { { "wavy beige", 5 } } },
      { "muted tomato", { { "striped red", 1 } } },
      { "dull blue",
        { { "plaid aqua", 1 }, { "dull coral", 3 }, { "posh yellow", 5 } } },
      { "dark plum",
        { { "bright lavender", 4 },
          { "dull black", 4 },
          { "clear silver", 4 },
          { "faded fuchsia", 2 } } },
      { "light tomato", { { "plaid white", 1 }, { "muted purple", 5 } } },
      { "wavy tomato",
        { { "vibrant teal", 4 }, { "plaid green", 1 }, { "dotted gold", 1 } } },
      { "pale white",
        { { "plaid tomato", 3 }, { "muted green", 3 }, { "light black", 4 } } },
      { "vibrant fuchsia",
        { { "shiny salmon", 1 },
          { "faded red", 3 },
          { "faded gray", 4 },
          { "drab turquoise", 4 } } },
      { "clear red", { { "vibrant olive", 2 } } },
      { "dull violet", { { "dim indigo", 5 } } },
      { "posh silver", { { "drab tomato", 1 } } },
      { "dark white",
        { { "vibrant green", 5 },
          { "mirrored gold", 3 },
          { "striped beige", 2 } } },
      { "mirrored maroon", { { "muted teal", 1 }, { "muted indigo", 1 } } },
      { "wavy cyan", { { "striped silver", 2 } } },
      { "plaid purple",
        { { "posh olive", 2 },
          { "vibrant salmon", 3 },
          { "bright silver", 1 } } },
      { "dull maroon", { { "plaid fuchsia", 5 }, { "striped gray", 1 } } },
      { "dark gold",
        { { "light red", 5 },
          { "plaid indigo", 4 },
          { "dim aqua", 1 },
          { "dark lavender", 5 } } },
      { "plaid brown",
        { { "shiny purple", 3 },
          { "mirrored lime", 4 },
          { "dark white", 3 } } },
      { "dotted tan", { { "striped olive", 4 } } },
      { "shiny purple", { { "faded indigo", 5 }, { "dim tan", 2 } } },
      { "clear lime", {} },
      { "posh turquoise",
        { { "drab gray", 4 },
          { "plaid crimson", 5 },
          { "striped silver", 4 } } },
      { "dotted brown", { { "dotted gold", 3 } } },
      { "striped violet", { { "dull white", 2 } } },
      { "striped green", { { "clear aqua", 4 }, { "posh tan", 4 } } },
      { "pale tomato",
        { { "dark maroon", 5 },
          { "faded indigo", 4 },
          { "dull turquoise", 4 },
          { "bright tomato", 1 } } },
      { "plaid coral",
        { { "dark tomato", 4 },
          { "pale purple", 1 },
          { "faded tan", 1 },
          { "dim tan", 5 } } },
      { "shiny cyan",
        { { "shiny magenta", 2 },
          { "dark lavender", 1 },
          { "vibrant blue", 2 } } },
      { "light yellow", { { "muted brown", 1 } } },
      { "dark orange",
        { { "dim brown", 2 },
          { "light beige", 5 },
          { "clear orange", 4 },
          { "dotted blue", 3 } } },
      { "drab violet", { { "light turquoise", 1 } } },
      { "wavy silver", { { "bright magenta", 3 }, { "clear salmon", 2 } } },
      { "clear magenta",
        { { "shiny black", 3 }, { "dim brown", 3 }, { "dim indigo", 4 } } },
      { "drab maroon",
        { { "posh maroon", 5 },
          { "clear orange", 3 },
          { "dotted coral", 3 } } },
      { "muted silver",
        { { "vibrant magenta", 3 },
          { "shiny lavender", 4 },
          { "posh crimson", 5 } } },
      { "pale gold",
        { { "light white", 1 },
          { "plaid chartreuse", 5 },
          { "striped magenta", 4 } } },
      { "muted turquoise", { { "mirrored turquoise", 1 } } },
      { "faded violet", { { "shiny indigo", 5 } } },
      { "clear crimson",
        { { "faded gray", 1 },
          { "vibrant silver", 5 },
          { "plaid blue", 5 },
          { "muted fuchsia", 1 } } },
      { "vibrant aqua", { { "dotted chartreuse", 3 } } },
      { "posh brown", { { "bright cyan", 2 }, { "shiny gold", 3 } } },
      { "faded magenta", { { "wavy yellow", 3 }, { "clear orange", 4 } } },
      { "posh maroon", { { "striped beige", 5 } } },
      { "dotted violet", { { "wavy gold", 4 } } },
      { "shiny red",
        { { "posh olive", 1 },
          { "vibrant green", 1 },
          { "muted purple", 4 } } },
      { "posh blue",
        { { "mirrored coral", 3 },
          { "shiny white", 1 },
          { "dotted salmon", 1 },
          { "vibrant silver", 5 } } },
      { "striped teal",
        { { "striped turquoise", 1 },
          { "faded black", 1 },
          { "muted green", 1 } } },
      { "wavy blue",
        { { "dull lavender", 4 },
          { "vibrant orange", 4 },
          { "plaid white", 2 },
          { "muted indigo", 5 } } },
      { "clear gold",
        { { "bright silver", 4 },
          { "clear red", 2 },
          { "dim aqua", 4 },
          { "dim crimson", 5 } } },
      { "shiny magenta", { { "plaid violet", 3 }, { "dotted lime", 4 } } },
      { "bright indigo", { { "muted green", 1 } } },
      { "clear white",
        { { "vibrant chartreuse", 2 },
          { "drab coral", 4 },
          { "bright cyan", 4 } } },
      { "clear aqua",
        { { "bright lavender", 1 },
          { "mirrored brown", 5 },
          { "drab green", 2 },
          { "muted maroon", 5 } } },
      { "posh magenta",
        { { "posh salmon", 4 },
          { "dull crimson", 3 },
          { "wavy violet", 5 },
          { "bright purple", 4 } } },
      { "plaid indigo", { { "dull maroon", 4 } } },
      { "pale magenta", { { "light black", 5 } } },
      { "plaid red",
        { { "mirrored gold", 3 },
          { "light tomato", 5 },
          { "wavy violet", 2 } } },
      { "striped olive",
        { { "posh maroon", 4 }, { "wavy black", 4 }, { "striped beige", 4 } } },
      { "drab blue",
        { { "faded black", 4 }, { "dark indigo", 3 }, { "dim violet", 4 } } },
      { "plaid bronze", { { "vibrant orange", 3 }, { "dark aqua", 3 } } },
      { "vibrant blue", {} },
      { "dark tan", { { "mirrored tomato", 5 } } },
      { "dotted purple",
        { { "muted brown", 4 },
          { "striped orange", 2 },
          { "dark green", 1 } } },
      { "mirrored white", { { "clear red", 1 } } },
      { "posh lime", { { "posh crimson", 2 } } },
      { "shiny orange", { { "dark fuchsia", 1 } } },
      { "faded olive", { { "vibrant teal", 4 } } },
      { "dull purple",
        { { "wavy orange", 3 },
          { "dim brown", 4 },
          { "shiny olive", 5 },
          { "bright beige", 2 } } },
      { "dark coral", { { "pale lime", 4 }, { "posh cyan", 2 } } },
      { "pale violet",
        { { "bright tomato", 4 },
          { "mirrored black", 5 },
          { "vibrant gold", 4 } } },
      { "light coral",
        { { "drab magenta", 5 },
          { "mirrored tomato", 2 },
          { "muted orange", 1 },
          { "clear maroon", 5 } } },
      { "pale green",
        { { "dim aqua", 2 }, { "dark fuchsia", 4 }, { "drab salmon", 2 } } },
      { "plaid gold",
        { { "dotted lime", 3 },
          { "faded indigo", 3 },
          { "striped turquoise", 5 },
          { "plaid chartreuse", 5 } } },
      { "dull orange",
        { { "mirrored coral", 4 },
          { "dotted maroon", 3 },
          { "striped orange", 5 },
          { "light green", 3 } } },
      { "shiny olive",
        { { "muted purple", 4 },
          { "plaid aqua", 4 },
          { "dotted blue", 3 },
          { "dotted teal", 5 } } },
      { "dim coral",
        { { "light purple", 2 },
          { "striped beige", 1 },
          { "striped indigo", 4 } } },
      { "mirrored gold",
        { { "vibrant blue", 1 },
          { "dotted teal", 1 },
          { "pale salmon", 1 },
          { "wavy gray", 3 } } },
      { "dim turquoise", { { "vibrant orange", 1 } } },
      { "dark teal", { { "dark chartreuse", 4 }, { "mirrored cyan", 5 } } },
      { "light silver", { { "striped red", 5 }, { "dim bronze", 3 } } },
      { "light blue", { { "light beige", 1 }, { "posh tomato", 3 } } },
      { "posh violet",
        { { "faded maroon", 2 },
          { "pale plum", 5 },
          { "dotted teal", 1 },
          { "dotted coral", 3 } } },
      { "plaid teal",
        { { "dotted chartreuse", 1 },
          { "posh turquoise", 4 },
          { "pale blue", 3 } } },
      { "faded lime", { { "mirrored gold", 5 }, { "plaid fuchsia", 2 } } },
      { "faded aqua",
        { { "dark tomato", 4 },
          { "posh olive", 3 },
          { "mirrored black", 4 },
          { "wavy salmon", 1 } } },
      { "mirrored beige", { { "striped lavender", 1 } } },
      { "vibrant indigo",
        { { "plaid fuchsia", 3 }, { "bright lavender", 1 } } },
      { "wavy tan",
        { { "drab coral", 5 },
          { "posh tomato", 5 },
          { "light fuchsia", 4 },
          { "striped tan", 3 } } },
      { "shiny crimson",
        { { "drab olive", 2 },
          { "bright chartreuse", 5 },
          { "faded magenta", 3 },
          { "mirrored salmon", 5 } } },
      { "dim tomato", { { "pale tan", 3 }, { "dotted maroon", 5 } } },
      { "clear indigo",
        { { "dotted gray", 2 },
          { "clear lime", 5 },
          { "muted teal", 1 },
          { "plaid green", 1 } } },
      { "vibrant brown", { { "vibrant beige", 1 } } },
      { "dotted cyan",
        { { "muted fuchsia", 1 },
          { "faded olive", 4 },
          { "mirrored lime", 4 } } },
      { "mirrored crimson",
        { { "dark indigo", 2 }, { "light coral", 4 }, { "dark silver", 5 } } },
      { "dim indigo", { { "plaid fuchsia", 1 } } },
      { "shiny teal", { { "shiny turquoise", 4 } } },
      { "striped lime",
        { { "clear purple", 1 },
          { "pale bronze", 3 },
          { "vibrant orange", 2 } } },
      { "light tan", { { "wavy gold", 1 }, { "light fuchsia", 1 } } },
      { "clear green", { { "faded olive", 1 }, { "vibrant coral", 2 } } },
      { "wavy black", { { "dotted teal", 5 }, { "dull fuchsia", 3 } } },
      { "wavy crimson", { { "shiny teal", 5 }, { "drab teal", 5 } } },
      { "shiny tomato",
        { { "clear chartreuse", 4 },
          { "muted teal", 5 },
          { "posh maroon", 3 } } },
      { "dotted plum", { { "dark chartreuse", 4 }, { "plaid orange", 5 } } },
      { "dull beige",
        { { "dim lavender", 5 },
          { "plaid magenta", 3 },
          { "dotted tan", 4 } } },
      { "drab teal",
        { { "posh silver", 3 }, { "shiny cyan", 1 }, { "bright teal", 1 } } },
      { "faded orange", { { "dark lime", 1 } } },
      { "pale cyan", { { "vibrant aqua", 4 } } },
      { "striped red", { { "dull fuchsia", 5 }, { "clear plum", 2 } } },
      { "mirrored green", { { "plaid orange", 3 }, { "dim aqua", 3 } } },
      { "faded tomato", { { "dim plum", 4 } } },
      { "clear salmon",
        { { "dim beige", 4 },
          { "clear beige", 4 },
          { "drab salmon", 4 },
          { "dull turquoise", 2 } } },
      { "vibrant tan",
        { { "wavy gold", 2 },
          { "plaid tan", 1 },
          { "wavy bronze", 1 },
          { "dull tomato", 4 } } },
      { "vibrant salmon",
        { { "plaid violet", 1 },
          { "plaid green", 5 },
          { "dark white", 4 },
          { "muted white", 2 } } },
      { "light chartreuse", { { "dull cyan", 3 }, { "mirrored fuchsia", 2 } } },
      { "mirrored bronze", { { "plaid white", 4 }, { "drab salmon", 1 } } },
      { "dull fuchsia", {} },
      { "mirrored lime",
        { { "dotted orange", 4 },
          { "faded tan", 5 },
          { "faded silver", 4 },
          { "plaid salmon", 5 } } },
      { "dotted aqua", { { "plaid green", 3 } } },
      { "drab brown",
        { { "dotted turquoise", 4 },
          { "plaid orange", 1 },
          { "striped silver", 2 } } },
      { "posh black", { { "faded turquoise", 5 }, { "dark lime", 2 } } },
      { "light violet", { { "bright lavender", 1 }, { "plaid crimson", 4 } } },
      { "drab fuchsia",
        { { "shiny beige", 1 }, { "dull tan", 3 }, { "shiny brown", 3 } } },
      { "dotted bronze",
        { { "light tomato", 4 },
          { "light blue", 2 },
          { "faded lavender", 1 },
          { "bright cyan", 5 } } },
      { "bright cyan", { { "dull olive", 4 } } },
      { "pale maroon", { { "dim aqua", 4 } } },
      { "bright magenta",
        { { "striped beige", 3 }, { "shiny gray", 3 }, { "clear plum", 4 } } },
      { "pale crimson",
        { { "dim blue", 5 },
          { "dotted fuchsia", 2 },
          { "shiny plum", 2 },
          { "muted fuchsia", 1 } } },
      { "vibrant teal",
        { { "dull gray", 5 }, { "drab coral", 5 }, { "clear orange", 3 } } },
      { "dotted maroon",
        { { "muted white", 1 }, { "dim orange", 2 }, { "vibrant blue", 4 } } },
      { "vibrant green", { { "plaid tan", 3 }, { "muted gray", 4 } } },
      { "plaid lavender", { { "pale gold", 1 }, { "shiny brown", 2 } } },
      { "plaid plum",
        { { "light salmon", 5 },
          { "clear indigo", 2 },
          { "faded bronze", 2 },
          { "drab violet", 2 } } },
      { "posh white", { { "dark purple", 2 }, { "faded plum", 2 } } },
      { "striped chartreuse",
        { { "dark turquoise", 4 },
          { "light beige", 4 },
          { "vibrant purple", 4 },
          { "bright bronze", 3 } } },
      { "dim gray", { { "light black", 4 }, { "plaid fuchsia", 1 } } },
      { "clear teal",
        { { "dotted fuchsia", 1 },
          { "dark silver", 4 },
          { "dark purple", 1 },
          { "light aqua", 5 } } },
      { "clear tan", { { "clear red", 3 } } },
      { "clear purple", { { "plaid orange", 3 }, { "muted brown", 2 } } },
      { "vibrant coral", { { "dull olive", 5 }, { "vibrant maroon", 2 } } },
      { "dim plum", { { "faded salmon", 2 }, { "dark green", 5 } } },
      { "dim cyan",
        { { "plaid fuchsia", 3 },
          { "dark crimson", 4 },
          { "muted indigo", 2 },
          { "pale lime", 2 } } },
      { "striped magenta",
        { { "clear orange", 1 }, { "dotted gray", 5 }, { "wavy gray", 2 } } },
      { "dotted beige",
        { { "shiny bronze", 4 },
          { "drab white", 4 },
          { "plaid indigo", 4 },
          { "plaid gold", 2 } } },
      { "dull green",
        { { "faded salmon", 2 },
          { "vibrant lavender", 5 },
          { "clear gold", 4 } } },
      { "light aqua", { { "bright lavender", 2 }, { "shiny gray", 4 } } },
      { "drab orange",
        { { "pale red", 2 }, { "vibrant bronze", 4 }, { "dim purple", 4 } } },
      { "posh yellow",
        { { "wavy bronze", 4 },
          { "light coral", 2 },
          { "faded chartreuse", 1 } } },
      { "drab coral",
        { { "mirrored gold", 4 },
          { "plaid tan", 2 },
          { "wavy black", 2 },
          { "striped beige", 2 } } },
      { "muted purple", {} },
      { "bright lime",
        { { "dotted violet", 3 },
          { "dotted teal", 2 },
          { "bright gray", 3 } } },
      { "muted black",
        { { "posh orange", 2 }, { "bright bronze", 1 }, { "clear lime", 1 } } },
      { "dotted olive",
        { { "vibrant violet", 1 },
          { "clear green", 5 },
          { "posh tomato", 4 } } },
      { "striped bronze",
        { { "pale teal", 4 }, { "faded yellow", 1 }, { "dull yellow", 5 } } },
      { "light magenta",
        { { "muted green", 1 },
          { "dim plum", 5 },
          { "bright tan", 2 },
          { "plaid indigo", 1 } } },
      { "pale lavender", { { "dotted blue", 3 } } },
      { "faded tan",
        { { "light lime", 1 }, { "faded black", 1 }, { "light fuchsia", 2 } } },
      { "mirrored coral",
        { { "dark white", 5 }, { "dark orange", 4 }, { "faded black", 5 } } },
      { "drab salmon",
        { { "dark turquoise", 2 },
          { "wavy plum", 3 },
          { "dotted chartreuse", 4 },
          { "light beige", 5 } } },
      { "muted aqua", { { "light beige", 3 } } },
      { "light cyan", { { "shiny coral", 1 }, { "vibrant silver", 5 } } },
      { "drab turquoise", { { "striped aqua", 1 }, { "drab lime", 1 } } },
      { "wavy indigo", { { "clear salmon", 2 }, { "dotted silver", 1 } } },
      { "shiny tan", { { "faded fuchsia", 2 }, { "faded black", 3 } } },
      { "shiny gray", { { "pale salmon", 5 }, { "shiny gold", 4 } } },
      { "vibrant black",
        { { "wavy orange", 3 },
          { "light purple", 3 },
          { "mirrored turquoise", 4 },
          { "drab tomato", 4 } } },
      { "dull gray", {} },
      { "dark salmon", { { "striped silver", 3 }, { "clear indigo", 4 } } },
      { "plaid black", { { "dim cyan", 3 }, { "bright beige", 2 } } },
      { "wavy gold",
        { { "drab coral", 4 },
          { "vibrant teal", 4 },
          { "clear orange", 4 },
          { "wavy black", 2 } } },
      { "light lavender",
        { { "bright plum", 4 },
          { "light violet", 3 },
          { "muted purple", 2 },
          { "posh orange", 4 } } },
      { "dark crimson",
        { { "plaid tan", 1 }, { "muted gray", 2 }, { "dotted teal", 5 } } },
      { "bright maroon",
        { { "striped red", 4 },
          { "drab maroon", 4 },
          { "bright magenta", 3 } } },
      { "dark purple", { { "clear plum", 1 }, { "dotted gold", 1 } } },
      { "dull salmon", { { "faded salmon", 2 } } },
      { "vibrant orange",
        { { "posh olive", 5 },
          { "dim cyan", 4 },
          { "striped beige", 5 },
          { "vibrant chartreuse", 2 } } },
      { "dark maroon", { { "posh brown", 1 }, { "dotted maroon", 3 } } },
      { "vibrant crimson",
        { { "plaid white", 3 },
          { "clear chartreuse", 1 },
          { "pale bronze", 5 },
          { "dotted brown", 4 } } },
      { "mirrored orange",
        { { "pale coral", 2 },
          { "faded indigo", 1 },
          { "dull red", 2 },
          { "light tan", 1 } } },
      { "bright red", { { "striped red", 2 }, { "posh tan", 5 } } },
      { "faded purple", { { "plaid aqua", 2 } } },
      { "muted green",
        { { "mirrored gold", 2 },
          { "vibrant indigo", 3 },
          { "dotted teal", 1 },
          { "striped tan", 3 } } },
      { "mirrored plum",
        { { "wavy fuchsia", 2 },
          { "faded turquoise", 1 },
          { "dim purple", 5 } } },
      { "dull brown",
        { { "striped tan", 2 },
          { "vibrant blue", 3 },
          { "vibrant white", 4 },
          { "dim chartreuse", 5 } } },
      { "faded salmon",
        { { "light red", 5 },
          { "pale indigo", 4 },
          { "posh bronze", 2 },
          { "dull turquoise", 1 } } },
      { "posh purple", { { "shiny lime", 3 } } },
      { "muted tan",
        { { "dark lime", 5 }, { "wavy tomato", 3 }, { "bright teal", 2 } } },
      { "dull cyan", { { "vibrant green", 3 }, { "bright maroon", 3 } } },
      { "drab white", { { "wavy black", 4 } } },
      { "striped black", { { "posh tan", 1 }, { "clear orange", 5 } } },
      { "mirrored yellow",
        { { "plaid turquoise", 4 },
          { "drab silver", 3 },
          { "dull tomato", 1 } } },
      { "dull red", { { "wavy olive", 4 } } },
      { "drab gray",
        { { "striped maroon", 2 },
          { "striped gray", 2 },
          { "drab cyan", 3 } } },
      { "faded teal",
        { { "bright bronze", 1 },
          { "clear tomato", 5 },
          { "dim orange", 5 },
          { "dim chartreuse", 4 } } },
      { "muted orange",
        { { "wavy maroon", 1 },
          { "bright tomato", 4 },
          { "light white", 1 },
          { "dotted coral", 2 } } },
      { "drab plum",
        { { "muted lavender", 2 },
          { "shiny magenta", 2 },
          { "posh red", 5 },
          { "bright fuchsia", 2 } } },
      { "faded maroon",
        { { "wavy tomato", 4 },
          { "dull brown", 1 },
          { "striped maroon", 4 },
          { "posh aqua", 3 } } },
      { "muted red", { { "dull tomato", 3 } } },
      { "mirrored aqua",
        { { "posh tomato", 5 }, { "muted teal", 4 }, { "drab green", 5 } } },
      { "dark brown", { { "vibrant aqua", 4 } } },
      { "plaid fuchsia", {} },
      { "posh tan",
        { { "clear plum", 4 }, { "posh orange", 2 }, { "wavy gray", 5 } } },
      { "striped turquoise", { { "dark aqua", 4 } } },
      { "drab lime",
        { { "posh brown", 5 },
          { "muted indigo", 5 },
          { "dotted maroon", 2 },
          { "clear lime", 2 } } },
      { "wavy teal",
        { { "mirrored red", 2 },
          { "bright lavender", 1 },
          { "dotted crimson", 5 },
          { "faded beige", 4 } } },
      { "shiny lavender",
        { { "clear purple", 5 },
          { "dim indigo", 4 },
          { "shiny plum", 4 },
          { "dull white", 1 } } },
      { "dull lime", { { "dim aqua", 1 }, { "shiny magenta", 1 } } },
      { "shiny maroon",
        { { "posh red", 5 },
          { "dim coral", 5 },
          { "clear crimson", 4 },
          { "bright lime", 2 } } },
      { "vibrant gray", { { "plaid cyan", 2 }, { "plaid lime", 4 } } },
      { "bright brown",
        { { "drab lavender", 1 },
          { "dim fuchsia", 1 },
          { "dim olive", 4 },
          { "wavy purple", 3 } } },
      { "bright green",
        { { "shiny red", 5 }, { "vibrant olive", 3 }, { "muted teal", 3 } } },
      { "vibrant beige", { { "clear olive", 4 }, { "striped black", 5 } } },
      { "drab olive",
        { { "vibrant white", 1 },
          { "drab brown", 5 },
          { "faded chartreuse", 5 },
          { "dark lime", 5 } } },
      { "wavy chartreuse",
        { { "dull gray", 1 },
          { "dull lavender", 1 },
          { "mirrored green", 1 },
          { "muted maroon", 2 } } },
      { "pale indigo", { { "bright beige", 5 }, { "dull crimson", 4 } } },
      { "dull tan",
        { { "bright lavender", 5 },
          { "bright cyan", 4 },
          { "dim maroon", 2 } } },
      { "vibrant violet", { { "dim violet", 4 } } },
      { "pale salmon", {} },
      { "shiny aqua", { { "plaid crimson", 2 }, { "mirrored red", 2 } } },
      { "pale black", { { "wavy chartreuse", 1 } } },
      { "drab bronze", { { "clear aqua", 5 }, { "pale brown", 3 } } },
      { "light white", { { "light tan", 1 }, { "dotted maroon", 3 } } },
      { "light green", { { "wavy olive", 3 } } },
      { "wavy yellow",
        { { "faded white", 3 },
          { "wavy plum", 5 },
          { "shiny turquoise", 1 } } },
      { "wavy violet", { { "pale salmon", 2 } } },
      { "striped salmon", { { "light turquoise", 5 }, { "muted tan", 4 } } },
      { "muted gold", { { "vibrant coral", 5 } } },
      { "clear plum", { { "vibrant green", 4 } } },
      { "striped purple", { { "posh red", 1 }, { "clear olive", 3 } } },
      { "dim lavender", { { "wavy plum", 5 } } },
      { "bright gold",
        { { "wavy brown", 3 },
          { "mirrored magenta", 2 },
          { "drab coral", 2 } } },
      { "plaid yellow", { { "plaid aqua", 2 }, { "pale salmon", 4 } } },
      { "mirrored blue", { { "posh orange", 4 } } },
      { "dull turquoise", { { "light teal", 5 }, { "striped green", 5 } } },
      { "bright aqua", { { "dotted lime", 4 } } },
      { "light olive", { { "wavy lavender", 3 }, { "wavy teal", 5 } } },
      { "pale chartreuse",
        { { "dark lime", 4 }, { "dim orange", 3 }, { "dotted maroon", 5 } } },
      { "dim magenta",
        { { "dark maroon", 1 },
          { "dull olive", 3 },
          { "dim tomato", 5 },
          { "wavy gold", 5 } } } }
};